name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      minio:
        image: minio/minio:latest
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        run: [ "server", "/data" ]
        ports:
          - 9000:9000
          - 9001:9001

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        cd django
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=postgres://django:django@localhost:5432/test_db" >> $GITHUB_ENV
        echo "MONGODB_URI=mongodb://localhost:27017" >> $GITHUB_ENV
        echo "MINIO_ENDPOINT=http://localhost:9000" >> $GITHUB_ENV
        echo "MINIO_ACCESS_KEY=minioadmin" >> $GITHUB_ENV
        echo "MINIO_SECRET_KEY=minioadmin" >> $GITHUB_ENV
        echo "DJANGO_SETTINGS_MODULE=django.ashian.settings" >> $GITHUB_ENV

    - name: Prepare the database
      env:
        DATABASE_URL: postgres://django:django@localhost:5432/test_db
      run: python manage.py migrate

    - name: Run tests
      env:
        DATABASE_URL: postgres://django:django@localhost:5432/test_db
        MONGODB_URI: mongodb://localhost:27017
        MINIO_ENDPOINT: http://localhost:9000
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
      run: python manage.py test